---
name: Super linter

on: [push, pull_request]

jobs:
  build:
    # Name the Job
    name: Super linter
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 # v8.2.1
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: '.*\.vscode/.*'
          VALIDATE_ANSIBLE: false
          VALIDATE_BASH: false
          VALIDATE_CHECKOV: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_BIOME_LINT: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_KUBERNETES_KUBECONFORM: false
          VALIDATE_BIOME_FORMAT: false
          # VALIDATE_NATURAL_LANGUAGE: false
          # VALIDATE_TEKTON: false
